{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: triton
  namespace: aegis-inference
  labels:
    app.kubernetes.io/name: triton
    app.kubernetes.io/part-of: aegisvision
  annotations:
    {{- if .Values.serviceAccount.eksRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.eksRoleArn | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
{{- end }}
