apiVersion: v1
kind: Service
metadata:
  name: pipeline-service
  namespace: aegis-system
  labels:
    app.kubernetes.io/name: pipeline-service
spec:
  selector:
    app.kubernetes.io/name: pipeline-service
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
      appProtocol: grpc
    - name: metrics
      port: 9091
      targetPort: 9091
