{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: console
  namespace: aegis-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: console
  minAvailable: {{ .Values.pdb.minAvailable }}
{{- end }}
