{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: console
  namespace: aegis-system
  labels:
    app.kubernetes.io/name: console
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: console
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
{{- end }}
